### ISSUE TITLE
[1JH] Intégration de service email au form de contact

### ISSUE THREAD

**Issue by claraxuxu** [vrn-sh/erp#123]
## Describe the issue
C'est une feature qui permet de lier le form de contact au backend, il va envoyer un mail à Voron après que l'utilisateur remplit le form

## Resource request
Discuter le text avec @bogdzn 

## Definition of done
- [x] Choisir une service de mail gratuit
- [x] Intégrer la service dans au front
- [x] Vérifier que Voron recevoir tous les champs de form
- [x] Vérifier que Voron recevoir la façon de contact de l'user
- [x] Mettre à jour les variables d'environnement dans env example

## testing plan
Remplir le form et voir si nous recevrons toutes les informations demandés

## JEH
1

**Comment by djnnvx** [comment]
we should also have an API endpoint in order to receive the emails. I will get working on it ASAP.
