### ISSUE TITLE
Set up front-end CI

### ISSUE THREAD

**Issue by hamid-yg** [vrn-sh/erp#18]
## Describe the issue
Set up Continuous Integration (CI) for the frontend

## Resource request
I will need @claraxuxu to decide which coding style we want to use

## Definition of done
- [x] setup a linter (eslint)
- [x] setup a code formatter
- [x] configure circleci or github actions to automatically check the code on some branches
- [x] setup a testing tool

## testing plan
The CI can be run automatically on some branches 

## JEH
1

**Comment by djnnvx** [comment]
@TheOrionsB proposed the [airbnb coding style](https://github.com/airbnb/javascript) if that is OK with you

**Comment by djnnvx** [comment]
Fixed in #58, thank u @TheOrionsB ! :)~
