### ISSUE TITLE
[1JH] check if user is log

### ISSUE THREAD

**Issue by Ananane** [vrn-sh/erp#199]
## Describe the issue
Vérifier sur chaque route s'il l'user est connecté et s'il ne l'est pas le rediriger sur la page login

## Definition of done
- [ ] Vérifier si l'user a bien login avec token, sinon redirect to login

## testing plan
Tester sur chaque route si ça fonctionne bien faire atttention à ne pas avoir de cookies stocker pour cette manip

## JEH
1

**Comment by claraxuxu** [comment]
y'a déjà une issue de ça  #181 , peux tu le close stp?

**Comment by Ananane** [comment]
Tu l'avais mise sur l'issue #180, je savais pas qu'il y en avait une autre
