### ISSUE TITLE
[1JH] Install docs

### ISSUE THREAD

**Issue by djnnvx** [vrn-sh/erp#21]
## Describe the issue 
New users of free tier should be able to install & run the app seamlessly. We need to provide an exhaustive install documentation in the README. We also need to describe the project, what it does, & what kind of features are supported (& on the roadmap).

We should also describe how users can contribute to issues & pull requests. 

## Resource request
@claraxuxu: is there any particular things users should be made aware of regarding the front-end ?

## Definition of done 

- [x] description of the project
- [x] feature request / issue guide
- [x] features description
- [x] roadmap
- [x] known issues / caveats

## Testing plan
n/a

## JEH
1

**Comment by claraxuxu** [comment]
Not for now, front can be run simply with the command "npm i & npm run dev"
