### ISSUE TITLE
[2JH] Loader front-end

### ISSUE THREAD

**Issue by claraxuxu** [vrn-sh/erp#306]
## Describe the issue
Quand Voron fait des demandes d'api, il n'y pas d'animations pendant le temps d'attente, ça sera sympa d'ajouter un petit loader pour montrer le progrès de demande afin d'améliorer l'user expérience 

## Definition of done
- [ ] Ajoute l'action loader dans les pages qui ont les demandes d'api (Djnn recommande: https://github.com/buunguyen/topbar, tu peux choisir ou créer un selon les besoins)

## testing plan
Describe here how the feature should be tested and demo should be done

## JEH
2

**Comment by djnnvx** [comment]
where is the PR for this ?

**Comment by Ananane** [comment]
je l'ai close parce qu'elle n'est pas dans le pld cette issue
