### ISSUE TITLE
Improve the team listing

### ISSUE THREAD

**Issue by TheOrionsB** [vrn-sh/erp#39]
## Describe the issue
It's a frontend improvement to the landing page

## Resource request
I don need nuthin

## Definition of done
- [x] Should be an animated caroussel
- [x] Contains a profile pic of the team member (avatar or pic idc)
- [x] Contains a name or nickname
- [x] Contains a short text written by the team member itself to describe their role in the project

## testing plan
Still need to figure testing with the team

## JEH
0.2 JEH

**Comment by djnnvx** [comment]
Closes with #43, good job bro)
