### ISSUE TITLE
[2JH] UI Vulnerability

### ISSUE THREAD

**Issue by claraxuxu** [vrn-sh/erp#45]
## Describe the issue
It's a simple form page

## Resource request
Should get the name of mission from the mission page, need to communicate with @samacamelia 
Will need to get the list of the vulnerability and impact from backend @bogdzn 

## Definition of done
- [ ] Should add a form into
- [ ] Should show the name correctly in the title of the form
- [ ] Should be able to add an image
- [ ] should import the list of vulnerability and impact to show the drop down list
- [ ] Button 'cancel' should bring user back to the Mission page

## testing plan
/

## JEH
2

**Comment by djnnvx** [comment]
Sure, let me know when you want to have a quick call, I can provide this no problem
