### ISSUE TITLE
[2JH] UI Profile Page

### ISSUE THREAD

**Issue by samacamelia** [vrn-sh/erp#65]
## Describe the issue
A page to view and edit the information of a pentester / manager

## Resource request
route backend to get user info @bogdzn 
Choose the location and add an icon to go to this page @claraxuxu 

## Definition of done
- user can view the information available in his profile 
- user can edit and save info

## testing plan
-unit test

## JEH
2

**Comment by djnnvx** [comment]
To get the full API specifications, you can just use `/docs` endpoint in the API in your browser. There is currently a crash on startup for the back-end but i'm working on it.

**Comment by djnnvx** [comment]
^ fixed in #70; please check docs once it's merged in `next` =)
